project:
  type: website
  output-dir: docs

format:
  revealjs:
    theme: simple
    footer: "Duke University - Department of Statistical Science"
    logo: images/logo.png
    transition: convex
    code-overflow: wrap
    code-line-numbers: true



